# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoAwsp < Formula
  desc ""
  homepage "https://github.com/abyss/go-awsp"
  version "1.0.1-test"

  on_macos do
    on_intel do
      url "https://github.com/abyss/go-awsp/releases/download/v1.0.1-test/go-awsp_Darwin_x86_64.tar.gz"
      sha256 "6871a15a6c92b1668c91b3f8d99881bbefa651b908ff449e20732ec62fe3fe9f"

      def install
        bin.install "go-awsp"
      end
    end
    on_arm do
      url "https://github.com/abyss/go-awsp/releases/download/v1.0.1-test/go-awsp_Darwin_arm64.tar.gz"
      sha256 "7280f6dc5e20837b15fff6fd566f129a7b4b0a884273c88f93072d0a70729d6f"

      def install
        bin.install "go-awsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/go-awsp/releases/download/v1.0.1-test/go-awsp_Linux_x86_64.tar.gz"
        sha256 "0b29dd9ca678c3b56f66b5e03729a106f48e58433ea991764df70d8076453e2b"

        def install
          bin.install "go-awsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/go-awsp/releases/download/v1.0.1-test/go-awsp_Linux_arm64.tar.gz"
        sha256 "8583712248fbfd4f581cfe0270bad6a2093c47649fe167619ae87c9ab45e1ca5"

        def install
          bin.install "go-awsp"
        end
      end
    end
  end
end
