# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsp < Formula
  desc "Easily switch between AWS Profiles with an interactive selector"
  homepage "https://github.com/abyss/go-awsp"
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/abyss/go-awsp/releases/download/v1.0.2/go-awsp_Darwin_x86_64.tar.gz"
      sha256 "2bd7d6df31c9f9326f0c211f399ca014ef7142241bf5df497510adf35fcc1fdc"

      def install
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
    on_arm do
      url "https://github.com/abyss/go-awsp/releases/download/v1.0.2/go-awsp_Darwin_arm64.tar.gz"
      sha256 "cb05a8fe9f41cc29919f0f61d9bd9327539c1e31146700db26e48fe821ad5ae9"

      def install
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/go-awsp/releases/download/v1.0.2/go-awsp_Linux_x86_64.tar.gz"
        sha256 "c5c131ee09ca16de56d16becfe71b9726ae074e7ae77aaa63cb20f3f2533c988"

        def install
          prefix.install "_source-awsp.sh"
          bin.install "go-awsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/go-awsp/releases/download/v1.0.2/go-awsp_Linux_arm64.tar.gz"
        sha256 "b7ee0ff7e4a28724182baf754a36c0f59b7f2b0aff1cd485d880ba968bdcb089"

        def install
          prefix.install "_source-awsp.sh"
          bin.install "go-awsp"
        end
      end
    end
  end

  def caveats
    <<~EOS
      ##################################################################

      To use awsp, add the following to your shell profile:
          alias awsp='source "$(brew --prefix awsp)/_source-awsp.sh"'

      ##################################################################
    EOS
  end
end
