# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awsp < Formula
  desc "Easily switch between AWS Profiles with an interactive selector"
  homepage "https://github.com/abyss/go-awsp"
  version "1.0.1"

  on_macos do
    on_intel do
      url "https://github.com/abyss/go-awsp/releases/download/v1.0.1/go-awsp_Darwin_x86_64.tar.gz"
      sha256 "592e18be51b078cc89927ddb0148b186e7f9146daa39e9faee0673b8252e09a5"

      def install
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
    on_arm do
      url "https://github.com/abyss/go-awsp/releases/download/v1.0.1/go-awsp_Darwin_arm64.tar.gz"
      sha256 "41569fc03091f56c04b954c80e8cd230a770b974156ce993eac4a2111a7af013"

      def install
        prefix.install "_source-awsp.sh"
        bin.install "go-awsp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/go-awsp/releases/download/v1.0.1/go-awsp_Linux_x86_64.tar.gz"
        sha256 "daf7e35a55c9528d6e2ffa67ef82831375ea4d30e6226f084eb92cdd33082fbb"

        def install
          prefix.install "_source-awsp.sh"
          bin.install "go-awsp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/go-awsp/releases/download/v1.0.1/go-awsp_Linux_arm64.tar.gz"
        sha256 "217f4751f3ed14e9f49eb5ee618f6c60263a3500ca8b34f40416d2462031f954"

        def install
          prefix.install "_source-awsp.sh"
          bin.install "go-awsp"
        end
      end
    end
  end

  def caveats
    <<~EOS
      ##################################################################

      To use awsp, add the following to your shell profile:
          alias awsp='source "$(brew --prefix awsp)/_source-awsp.sh"'

      ##################################################################
    EOS
  end
end
