# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfws < Formula
  desc "Interactive Terraform workspace selector"
  homepage "https://github.com/abyss/tfws"
  version "1.0.3"

  on_macos do
    on_intel do
      url "https://github.com/abyss/tfws/releases/download/v1.0.3/tfws_Darwin_x86_64.tar.gz"
      sha256 "bd85a1a6a6efc496ad164650631c40148661d56ec6538618479e72b0e38fbb35"

      def install
        bin.install "tfws"
      end
    end
    on_arm do
      url "https://github.com/abyss/tfws/releases/download/v1.0.3/tfws_Darwin_arm64.tar.gz"
      sha256 "91a24358b8250428008aeea3cfcecce9815680cf7e201fcc9643289f2ecee194"

      def install
        bin.install "tfws"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/tfws/releases/download/v1.0.3/tfws_Linux_x86_64.tar.gz"
        sha256 "4695ac851726156ff88a30c91703d1144fa08220a2cd21175926e153924468b4"

        def install
          bin.install "tfws"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/abyss/tfws/releases/download/v1.0.3/tfws_Linux_arm64.tar.gz"
        sha256 "e32059dc109664f06cdb7cb389265df270dbaf0b63bdbd90ef15ec5768f99dc9"

        def install
          bin.install "tfws"
        end
      end
    end
  end
end
